# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: best_practice_project 0.0.11 ruby lib

Gem::Specification.new do |s|
  s.name = "best_practice_project".freeze
  s.version = "0.0.11"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["kaspernj".freeze]
  s.date = "2019-10-21"
  s.description = "A bundle of various linters and code inspection tools".freeze
  s.email = "k@spernj.org".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop.yml",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "best_practice_project.gemspec",
    "lib/best_practice_project.rb",
    "lib/best_practice_project/base_handler.rb",
    "lib/best_practice_project/coffee_lint_handler.rb",
    "lib/best_practice_project/config/haml-lint.yml",
    "lib/best_practice_project/config/rails_best_practices.yml",
    "lib/best_practice_project/config/rubocop.yml",
    "lib/best_practice_project/haml_lint_handler.rb",
    "lib/best_practice_project/rails_best_practices_handler.rb",
    "lib/best_practice_project/rubocop_handler.rb",
    "lib/best_practice_project/scss_lint_handler.rb",
    "lib/tasks/best_practice_project.rake",
    "peak_flow.yml",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kaspernj/best_practice_project".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.6".freeze
  s.summary = "A bundle of various linters and code inspection tools".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<auto_autoloader>.freeze, [">= 0.0.5"])
      s.add_development_dependency(%q<juwelier>.freeze, [">= 0"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_development_dependency(%q<rubocop>.freeze, [">= 0"])
      s.add_development_dependency(%q<rubocop-performance>.freeze, [">= 0"])
      s.add_development_dependency(%q<rubocop-rails>.freeze, [">= 0"])
      s.add_development_dependency(%q<rubocop-rspec>.freeze, [">= 0"])
    else
      s.add_dependency(%q<auto_autoloader>.freeze, [">= 0.0.5"])
      s.add_dependency(%q<juwelier>.freeze, [">= 0"])
      s.add_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_dependency(%q<rubocop>.freeze, [">= 0"])
      s.add_dependency(%q<rubocop-performance>.freeze, [">= 0"])
      s.add_dependency(%q<rubocop-rails>.freeze, [">= 0"])
      s.add_dependency(%q<rubocop-rspec>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<auto_autoloader>.freeze, [">= 0.0.5"])
    s.add_dependency(%q<juwelier>.freeze, [">= 0"])
    s.add_dependency(%q<bundler>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, [">= 0"])
    s.add_dependency(%q<rubocop>.freeze, [">= 0"])
    s.add_dependency(%q<rubocop-performance>.freeze, [">= 0"])
    s.add_dependency(%q<rubocop-rails>.freeze, [">= 0"])
    s.add_dependency(%q<rubocop-rspec>.freeze, [">= 0"])
  end
end

